/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import React, { useRef } from "react";
import { useLoader } from "react-three-fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import { draco } from "drei";

function Model({ metalness = 0, roughness = 0.8, transmission = 1, ...props }) {
  const group = useRef();

  const { nodes, materials } = useLoader(
    GLTFLoader,
    "/tv3.glb",
    draco("/draco-gltf/")
  );

  const materialProps = {
    clearcoat: 1.0,
    clearcoatRoughness: 0,
    roughness,
    metalness,
    color: 0xaaaaaa,
    transmission,
    opacity: 1,
    transparent: true,
  };

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials.TV_1970_Mat}
        geometry={nodes.TV_1970_TV_1970_Mat_0.geometry}
        position={[-3.37, 0, 0.12]}
        receiveShadow
        castShadow
      />
      <group position={[-3.37, 0, 0.12]}>
        <mesh geometry={nodes.TV_1970_TV_1970_Mat_0001.geometry}>
          <meshPhysicalMaterial {...materialProps} />
        </mesh>
      </group>
    </group>
  );
}

export default Model;
